name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH Connection
        run: |
          mkdir -p /home/runner/.ssh
          chmod 700 /home/runner/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" | tee /home/runner/.ssh/id_rsa > /dev/null
          chmod 600 /home/runner/.ssh/id_rsa
          ssh-keyscan -H 13.229.75.55 | tee -a /home/runner/.ssh/known_hosts > /dev/null

      - name: Deploy to EC2
        run: |
          ssh -i /home/runner/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@13.229.75.55 << 'EOF'
            cd /home/ubuntu/sync-backend
            git pull origin main
            npm install
            pm2 restart all
          EOF
