name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Change if using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH Connection
        run: |
          sudo mkdir -p /tmp/ssh
          sudo chmod 700 /tmp/ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" | tee /tmp/ssh/id_rsa > /dev/null
          sudo chmod 600 /tmp/ssh/id_rsa
          ssh-keyscan -H 13.229.75.55 | tee -a /tmp/ssh/known_hosts > /dev/null

      - name: Deploy to EC2
        run: |
          ssh -i /tmp/ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@13.229.75.55 << 'EOF'
            cd /home/ubuntu/sync-backend
            git pull origin main
            npm install
            pm2 restart all
          EOF
